theme: jekyll-theme-slate
domain: coronanet-working-paper-series.github.io
url: https://coronanet-working-paper-series.github.io
title: CoronaNet Working Paper Series
description: Articles published as a part of the CoronaNet Working Paper Series
repository: coronanet-working-paper-series/coronanet-working-paper-series.github.io
